module.exports = [
  {
    id: 1,
    displayName: 'BlueVioletMiniBaker',
    commentText: 'Cool, great! ☺\nDiamond 💎',
    // new Date(year, monthIndex [, day [, hours [, minutes [, seconds [, milliseconds]]]]]);
    // The argument monthIndex is 0-based. This means that January = 0 and December = 11.
    timestamp: new Date(2018, 3, 16, 15, 15, 0),
    numUpVotes: 1,
    numDownVotes: 0,
    // displayName, replyText, timestamp, numUpVotes, numDownVotes,
    replies: [
      {
        id: 1,
        displayName: 'Dummy',
        replyText: 'This is a dummy reply.',
        timestamp: new Date(2018, 3, 16, 16, 52, 0),
        numUpVotes: 0,
        numDownVotes: 0,
      },
      {
        id: 2,
        displayName: 'Dummy2',
        replyText: 'This is a second dummy reply.',
        timestamp: new Date(2018, 3, 16, 16, 55, 0),
        numUpVotes: 0,
        numDownVotes: 0,
      },
    ],
  },
  {
    id: 2,
    displayName: 'BlueCosmicGymnast12',
    commentText: 'Cool,I loved the part with are the superheroes real!😂\n\n🌠✨Cosmo🌟🌠\n💙🦅Ravenclaw🦅💙\n🌸🌵Cosmo Quotes and Facts🌵🌸',
    timestamp: new Date(2018, 3, 16, 16, 52, 0),
    numUpVotes: 2,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 3,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 4,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 5,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 6,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 7,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 8,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 9,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 10,
    displayName: 'Bob Ross',
    commentText: 'But we\'re not there yet, so we don\'t need to worry about it. You can\'t have light without dark. You can\'t know happiness unless you\'ve known sorrow.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
];

