module.exports = [
  {
    id: 1,
    displayName: 'AprilShowers13',
    commentText: 'can\'t wait for the next avengers to come out!!!!',
    // new Date(year, monthIndex [, day [, hours [, minutes [, seconds [, milliseconds]]]]]);
    // The argument monthIndex is 0-based. This means that January = 0 and December = 11.
    timestamp: new Date(2018, 3, 16, 15, 15, 0),
    numUpVotes: 1,
    numDownVotes: 0,
    // displayName, replyText, timestamp, numUpVotes, numDownVotes,
    replies: [
      {
        id: 1,
        displayName: 'Dummy',
        replyText: 'This is a dummy reply.',
        timestamp: new Date(2018, 3, 16, 16, 52, 0),
        numUpVotes: 0,
        numDownVotes: 0,
      },
      {
        id: 2,
        displayName: 'Dummy2',
        replyText: 'This is a second dummy reply.',
        timestamp: new Date(2018, 3, 16, 16, 55, 0),
        numUpVotes: 0,
        numDownVotes: 0,
      },
    ],
  },
  {
    id: 2,
    displayName: 'U17035666',
    commentText: 'i love the Avengers',
    timestamp: new Date(2018, 3, 16, 16, 52, 0),
    numUpVotes: 2,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 3,
    displayName: 'HarryPotterFan',
    commentText: 'Elizabeth Olsen was so funny when she bent her thumbs right the way back!',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 4,
    displayName: 'U17011742',
    commentText: 'matter eater lad whaaaaat',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 5,
    displayName: 'DiamondSnowKitten',
    commentText: 'I can\'t believe there\'s a superhero that turns into ice cream. Useless superpower...\nBy the way StarstoneViolinChimp yes the guardians of the galaxy are in Infinity WarBy the way StarstoneViolinChimp yes the guardians of the galaxy are in Infinity War',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 6,
    displayName: 'DiamondSnowKitten',
    commentText: 'I love Marvel and Avengers Infinity War was one of their best movies. Can\'t wait for the sequel and the rest of phase 4',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 7,
    displayName: 'SwimmingPengiun',
    commentText: 'Cool 🙂👍❤️',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 8,
    displayName: 'jelly_ferret',
    commentText: 'Scarlet Witch is my favourite super hero! And 2 of my 3 favourite actors were in this !!',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 9,
    displayName: 'redguitar10',
    commentText: 'I absolutely love all the avengers! So amazing!',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 10,
    displayName: 'DancingBluePotato',
    commentText: 'Aren\'t the Guardians of the Galaxy supposed to be in this film? I\'ve completely forgot lol 😂\nViolin 🎻',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 11,
    displayName: 'Unicorn22',
    commentText: 'I absolutely love marvel and all the avengers! 💕 But I’m sad Tom Holland isn\'t there',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [
      {
        id: 1,
        displayName: 'DJ_SnowflakeDiva',
        replyText: '@Unicorn22\nI agree *crying on the inside* 😂\n\n👑❄🔥🎶 DJ Ash 🎶🔥❄👑\n😎🐍👑 #SlytherinQueen 👑🐍😎\n👻🎉😱🎆BP\'sOctoberFoTM2017🎆😱🎉👻',
        timestamp: new Date(2018, 3, 16, 16, 52, 0),
        numUpVotes: 0,
        numDownVotes: 0,
      },
    ],
  },
  {
    id: 12,
    displayName: 'DJ_SnowflakeDiva',
    commentText: 'Absolutely love this!! I am literally obsessed with the Avengers right now!\n👑❄🔥🎶 DJ Ash 🎶🔥❄👑',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 13,
    displayName: 'U16987021',
    commentText: 'Can\'t wait for Avengers Infinity Wars so cool!!! YAY.',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 14,
    displayName: 'PottyAboutPotter',
    commentText: 'Lol love Doctor Strange he is so awesome',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 15,
    displayName: 'OrangeSummerySeal',
    commentText: 'Oh Tom Holland wasn\'t there\n\nDoes anyone know Tom Holland?',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [
      {
        id: 1,
        displayName: 'DJ_SnowflakeDiva',
        replyText: '@OrangeSummerySeal\nYep, Tom Holland (AKA: SpiderMan) is on Infinity War. But so is Chris Evans (AKA: Captain America) and Robert Downey Jr (AKA: Iron Man). So maybe they just were *sadly* busy at the time of the interview 😔\nHope this helps!',
        timestamp: new Date(2018, 3, 16, 16, 52, 0),
        numUpVotes: 0,
        numDownVotes: 0,
      },
    ],
  },
  {
    id: 16,
    displayName: 'BlueCosmicGymnast12',
    commentText: 'Cool, I loved the part with are the superheroes real!😂\n\n🌠✨Cosmo🌟🌠\n💙🦅Ravenclaw🦅💙\n🌸🌵Cosmo Quotes and Facts🌵🌸',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
  {
    id: 17,
    displayName: 'BlueVioletMiniBaker',
    commentText: 'Cool, great!☺\nDiamond 💎',
    timestamp: new Date(2018, 3, 20, 20, 24, 0),
    numUpVotes: 0,
    numDownVotes: 0,
    replies: [],
  },
];
